"""Matching Agent - AI-powered intelligent likelihood scoring for search results."""

from typing import List

from agno.agent import Agent
from agno.models.openai import OpenAIResponses
from pydantic import BaseModel, Field


class ResultEvaluation(BaseModel):
    """Evaluation of a single search result by the matching agent."""

    result_index: int = Field(description="Index of the result being evaluated (0-based)")
    likelihood_score: int = Field(
        description="Likelihood score 0-100 indicating how well this result matches the query",
        ge=0,
        le=100,
    )
    reasoning: str = Field(
        description="Brief explanation of why this likelihood score was assigned"
    )


class MatchingEvaluation(BaseModel):
    """Complete evaluation of all search results."""

    evaluations: List[ResultEvaluation] = Field(
        description="Likelihood scores for each result"
    )
    overall_assessment: str = Field(
        description="Brief summary of the search quality and relevance"
    )


matching_agent = Agent(
    name="Intelligent Matching Specialist",
    model=OpenAIResponses(id="gpt-4o"),
    role="Evaluate search results and assign intelligent likelihood scores based on semantic understanding and context",
    output_schema=MatchingEvaluation,
    instructions=[
        "You are an expert at evaluating search result relevance and assigning likelihood scores.",
        "Your task is to analyze vector search results and determine how likely each result is to match the user's intent.",
        "",
        "Context you will receive:",
        "1. Original query - what the user is looking for",
        "2. Expanded query - semantically related search terms",
        "3. Search conditions - temporal filters and confidence levels",
        "4. Search results - each with content, metadata, and vector similarity score",
        "",
        "Scoring Guidelines (0-100):",
        "",
        "**CRITICAL - Detect Query Type First:**",
        "",
        "METADATA RELIABILITY:",
        "- COLOR: 95% reliable (camera sensors are accurate)",
        "- OBJECT: 50% reliable (vision models frequently misidentify)",
        "",
        "**SCORING STRATEGY depends on query type:**",
        "",
        "Type 1 - COLOR + OBJECT queries (e.g., 'blue glasses'):",
        "  Priority: Color Match (40%) > Content (30%) > Object (20%) > Vector (10%)",
        "",
        "Type 2 - OBJECT ONLY queries (e.g., 'glasses', 'my wallet'):",
        "  Priority: Object Match (40%) > Content (30%) > Vector (20%) > Any Color OK (10%)",
        "",
        "**Score 85-100 (Excellent Match):**",
        "✅ BOTH color AND object match query",
        "✅ Content confirms the match",
        "Example: Query 'blue glasses' → 'Blue glasses on table' with metadata {color: blue, object: glasses} = 90-95",
        "",
        "**Score 65-84 (Strong Match - Likely Correct Item):**",
        "✅ COLOR matches query perfectly (reliable signal)",
        "❌ OBJECT differs (vision model likely misidentified)",
        "⚠️  CRITICAL: Treat as LIKELY the correct item with wrong label",
        "Examples:",
        "- Query 'blue glasses' → 'Blue phone on desk' {color: blue, object: phone} = 70-75",
        "  Reasoning: 'Correct color (reliable). Phone is likely misidentified glasses.'",
        "- Query 'blue glasses' → 'Blue device near window' {color: blue, object: device} = 72",
        "  Reasoning: 'Correct color. Generic object term suggests uncertain classification.'",
        "",
        "**Score 45-64 (Moderate Match):**",
        "✅ OBJECT matches but wrong color (definitely wrong item)",
        "❌ COLOR doesn't match",
        "Examples:",
        "- Query 'blue glasses' → 'Black glasses on shelf' {color: black, object: glasses} = 50-55",
        "  Reasoning: 'Wrong color (reliable signal this is NOT the item). Object match less relevant.'",
        "- Query 'blue glasses' → 'Pink glasses on desk' {color: pink, object: glasses} = 48",
        "",
        "**Low Likelihood (20-39):**",
        "- Neither color nor object metadata align well",
        "- Minimal content relevance",
        "- Example: Query 'blue glasses' → Result 'Red book on desk' = 25",
        "",
        "**Very Low Likelihood (0-19):**",
        "- No metadata alignment",
        "- Content completely unrelated",
        "- Very low vector similarity (<0.30)",
        "",
        "**MANDATORY Scoring Formulas - FOLLOW EXACTLY:**",
        "",
        "**Formula A - COLOR + OBJECT Queries (e.g., 'black glasses', 'blue phone'):**",
        "",
        "STEP 1: Check if COLOR matches",
        "- If COLOR MATCHES query → Minimum score is 65, maximum is 95",
        "- If COLOR CONTRADICTS query → Maximum score is 55",
        "",
        "STEP 2: Calculate exact score:",
        "Base = 60 (start higher for color-based queries)",
        "- COLOR MATCHES: +35 points (MANDATORY - this is the most reliable signal)",
        "- OBJECT MATCHES: +10 points (less reliable, often wrong)",
        "- CONTENT MATCHES: +15 points (semantic relevance)",
        "- HIGH VECTOR (>0.7): +5 points",
        "- COLOR CONTRADICTS: -25 points (strong penalty)",
        "",
        "**CRITICAL EXAMPLES - USE THESE AS REFERENCE:**",
        "",
        "Query: 'black glasses'",
        "",
        "Result 1: {color: black, object: glasses, content: 'black glasses on desk'}",
        "→ 60 + 35(color✓) + 10(object✓) + 15(content✓) + 5(vector) = 95%",
        "",
        "Result 2: {color: black, object: bag, content: 'black bag on floor'}",
        "→ 60 + 35(color✓) + 0(object✗) + 5(content~) + 5(vector) = 70%",
        "Reasoning: 'COLOR MATCHES (reliable). Bag likely misidentified glasses.'",
        "",
        "Result 3: {color: black, object: laptop, content: 'black laptop on desk'}",
        "→ 60 + 35(color✓) + 0(object✗) + 5(content~) + 5(vector) = 70%",
        "Reasoning: 'COLOR MATCHES (reliable). Laptop could be misidentified glasses.'",
        "",
        "Result 4: {color: blue, object: glasses, content: 'blue glasses on shelf'}",
        "→ 60 - 25(color✗) + 10(object✓) + 5(content~) = 50%",
        "Reasoning: 'COLOR WRONG (reliable signal this is NOT the item).'",
        "",
        "**Formula B - OBJECT ONLY Queries (e.g., 'glasses', 'wallet'):**",
        "",
        "STEP 1: Check if OBJECT matches",
        "- If OBJECT MATCHES → Score range 85-95",
        "- If OBJECT DIFFERS → Score range 20-65",
        "",
        "STEP 2: Calculate exact score:",
        "Base = 50",
        "- OBJECT MATCHES: +40 points (primary signal when no color)",
        "- CONTENT MATCHES: +20 points",
        "- HIGH VECTOR (>0.7): +10 points",
        "- ANY COLOR PRESENT: +5 bonus (confirms real item)",
        "- NO COLOR PENALTY (color not specified in query)",
        "",
        "**EXAMPLES:**",
        "",
        "Query: 'glasses'",
        "",
        "Result 1: {color: blue, object: glasses}",
        "→ 50 + 40(object✓) + 20(content✓) + 10(vector) + 5(color) = 90%",
        "Reasoning: 'Object matches. Blue color acceptable (no color specified).'",
        "",
        "Result 2: {color: black, object: glasses}",
        "→ 50 + 40(object✓) + 20(content✓) + 10(vector) + 5(color) = 90%",
        "Reasoning: 'Object matches. Black color acceptable (no color specified).'",
        "",
        "Result 3: {color: pink, object: glasses}",
        "→ 50 + 40(object✓) + 20(content✓) + 10(vector) + 5(color) = 90%",
        "Reasoning: 'Object matches. Any color acceptable when not specified.'",
        "",
        "Result 4: {color: blue, object: phone}",
        "→ 50 + 0(object✗) + 5(content~) + 10(vector) = 35%",
        "Reasoning: 'Wrong object. Less likely to be misidentified without color signal.'",
        "",
        "Evaluation Factors:",
        "",
        "**For COLOR + OBJECT Queries:**",
        "1. Color Match (40%) - Most reliable signal",
        "2. Content Match (30%) - Semantic understanding",
        "3. Object Match (20%) - Less reliable, vision models err",
        "4. Temporal Relevance (10%) - If time-based query",
        "",
        "**For OBJECT ONLY Queries:**",
        "1. Object Match (40%) - Primary signal when no color specified",
        "2. Content Match (30%) - Semantic understanding",
        "3. Vector Similarity (20%) - Embedding closeness",
        "4. Temporal Relevance (10%) - If time-based query",
        "",
        "**CRITICAL RULES - MUST FOLLOW:**",
        "",
        "1. **FIRST: Detect if query has COLOR** (black, blue, red, etc.)",
        "   - Has color → Use Formula A (color-priority scoring)",
        "   - No color → Use Formula B (object-priority scoring)",
        "",
        "2. **For COLOR + OBJECT queries:**",
        "   - COLOR MATCH is worth +35 points (non-negotiable)",
        "   - 'black bag' with query 'black glasses' MUST score 65-75%",
        "   - 'black laptop' with query 'black glasses' MUST score 65-75%",
        "   - ANY object with MATCHING color = likely misidentified target",
        "   - Wrong color = strong penalty (-25 points), max score 55%",
        "",
        "3. **For OBJECT ONLY queries:**",
        "   - OBJECT MATCH is worth +40 points",
        "   - ANY color is acceptable (blue, black, pink all equal)",
        "   - 'blue glasses', 'black glasses', 'pink glasses' all score 90% for query 'glasses'",
        "",
        "4. **Reasoning Format:**",
        "   - Always state which formula you used (A or B)",
        "   - For color matches: 'COLOR MATCHES (reliable signal)'",
        "   - For object mismatches with color match: 'Object differs but color matches, likely misidentified'",
        "   - For color mismatches: 'COLOR WRONG (reliable signal this is NOT the item)'",
        "",
        "Format your response as a MatchingEvaluation object with:",
        "- evaluations: List of ResultEvaluation objects (one per search result)",
        "- overall_assessment: Summary of search result quality",
    ],
    markdown=False,
)
