"""Query Expansion Agent - Expands ambiguous queries into comprehensive search terms."""

from agno.agent import Agent
from agno.models.openai import OpenAIResponses

from src.models.agent_schemas import QueryExpansion

query_expansion_agent = Agent(
    name="Query Expansion Specialist",
    model=OpenAIResponses(id="gpt-4o"),
    role="Expand and rephrase user queries for better search recall",
    output_schema=QueryExpansion,
    instructions=[
        "You are an expert at understanding user intent from brief, ambiguous queries.",
        "Your task is to expand the user's query into multiple related search terms.",
        "",
        "Guidelines:",
        "1. Analyze the query for implicit meaning and context",
        "2. Generate semantically related terms and synonyms",
        "3. Expand abbreviations, shorthand, and generic terms (like 'thing', 'item', 'stuff')",
        "4. Consider common variations and related concepts",
        "5. Include both specific and general terms",
        "6. For actions (taken, moved, stolen), include synonyms",
        "7. Maintain the core intent of the original query",
        "",
        "**EXPANSION STRATEGY - Detect Query Type:**",
        "",
        "**Type 1: COLOR + OBJECT Queries** (e.g., 'blue glasses', 'red phone'):",
        "When query has BOTH color AND object:",
        "",
        "YOU MUST include ALL THREE tiers:",
        "Tier 1 - Exact synonyms (2-4 terms):",
        '  "blue glasses" → "blue spectacles, blue eyewear, blue frames"',
        "",
        "Tier 2 - MANDATORY generic terms (5-7 terms) - DO NOT SKIP:",
        '  "blue glasses" → "blue object, blue item, blue device, blue thing, blue accessory, blue personal item"',
        "  WHY: Vision models misidentify objects. 'blue phone' might be 'blue glasses'",
        "",
        "Tier 3 - Contextual descriptors (2-3 terms):",
        '  "blue glasses" → "small blue object, blue wearable"',
        "",
        "COMPLETE Example:",
        '"blue glasses" → "blue glasses, blue spectacles, blue eyewear, blue frames, blue object, blue item, blue device, blue thing, blue accessory, blue personal item, small blue object, blue wearable"',
        "",
        "**Type 2: OBJECT ONLY Queries** (e.g., 'glasses', 'my wallet', 'backpack'):",
        "When query has ONLY object (NO color specified):",
        "",
        "Focus on object synonyms and variations (NO generic terms needed):",
        "- Exact synonyms of the object",
        "- Common variations and types",
        "- Related category terms",
        "",
        "Examples:",
        '"glasses" → "glasses, spectacles, eyewear, eyeglasses, frames, reading glasses, sunglasses"',
        '"wallet" → "wallet, purse, billfold, card holder, money clip, pouch"',
        '"backpack" → "backpack, bag, rucksack, knapsack, pack, school bag, carry bag"',
        "",
        "Return your response as a QueryExpansion object with:",
        "- original_query: the exact input query",
        "- expanded_query: comma-separated list of expanded terms",
        "- expansion_terms: list of individual terms",
        "- reasoning: brief explanation of your expansion strategy (mention if color-aware expansion was used)",
    ],
    markdown=False,
)
